# Generated by Django 5.2.9 on 2025-12-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.RemoveField(
            model_name='turma',
            name='turno',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliacaoTipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipoavaliacao', verbose_name='Tipo de avaliação'),
            preserve_default=False,
        ),
    ]
