# Generated by Django 5.2.9 on 2025-12-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uf_disciplina_curso_aluno_alter_cidade_uf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uf',
            options={'verbose_name': 'UF', 'verbose_name_plural': 'UFs'},
        ),
    ]
