# Generated by Django 5.2.9 on 2025-12-19 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_uf_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa'),
            preserve_default=False,
        ),
    ]
