# Generated by Django 5.2.9 on 2025-12-19 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_aluno_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.aluno', verbose_name='Aluno'),
            preserve_default=False,
        ),
    ]
