# Generated by Django 5.2.9 on 2025-12-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_matricula_pessoa_matricula_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='data_nasc',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome_da_mae',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome_do_pai',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ocupacao',
        ),
    ]
